% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={rapport},
  pdfauthor={ghada},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{rapport}
\author{ghada}
\date{2026-05-14}

\begin{document}
\maketitle

\section{1 Introduction}\label{introduction}

\subsection{1.1 Contexte du projet}\label{contexte-du-projet}

Dans le domaine des sciences du sport, de la santé publique et de la
biométrie, l'analyse statistique des données physiologiques et
anthropométriques joue un rôle fondamental dans la compréhension des
détermi nants de la condition physique humaine. Les indicateurs tels que
l'âge, l'indice de masse corporelle (IMC), le pourcentage de masse
grasse, la force musculaire, l'endurance et la capacité cardiovasculaire
sont largement utilisés pour évaluer l'état de santé et le niveau de
forme physique des individus. Cependant, ces variables présentent
souvent des distributions complexes, influencées par des facteurs bi
ologiques, sociaux et comportementaux, notamment le sexe. L'étude
statistique rigoureuse de ces données nécessite donc l'utilisation
conjointe de méthodes descriptives, de tests de normalité et de tests
paramétriques et non paramétriques permettant d'identifier les relations
significatives entre les variables. Dans ce contexte, le présent projet
s'inscrit dans une démarche d'analyse statistique approfondie d'un jeu
de données réel contenant des informations démographiques,
anthropométriques et des mesures de performance physique. Ce travail
vise à appliquer différentes techniques statistiques afin de valider des
hypothèses, d'évaluer la structure des données et de comparer les
groupes selon des variables pertinentes. Ce projet constitue également
une application pratique des concepts théoriques abordés dans le cadre
du cours de statistique, en mettant l'accent sur la rigueur
méthodologique, l'interprétation correcte des résultats et la
justification du choix des tests statistiques utilisés.

\subsection{1.2 Objectif du projet}\label{objectif-du-projet}

L'objectif principal de ce projet est de réaliser une analyse
statistique complète et structurée d'un ensem ble de données
physiologiques et anthropométriques, en vue de mieux comprendre les
relations entre les caractéristiques individuelles et les performances
physiques. Plus précisément, ce projet vise à : • Explorer et décrire
les données à l'aide de statistiques descriptives afin d'identifier les
tendances cen trales, la dispersion et la structure globale des
variables étudiées. • Vérifier les hypothèses de normalité des variables
quantitatives à l'aide de tests statistiques appropriés, notamment le
test de Shapiro--Wilk, afin de justifier le choix des méthodes
paramétriques ou non paramétriques. • Détecter et analyser les valeurs
aberrantes susceptibles d'influencer les résultats statistiques. •
Comparer les groupes définis par la variable sexe à l'aide de tests
paramétriques (tests t, ANOVA, tests de proportion) et non paramétriques
(tests de Wilcoxon, tests des signes), selon la nature et la
distribution des données. • Étudier les relations entre les variables à
travers l'analyse des corrélations et l'évaluation de leur
significativité statistique. Àtravers ces objectifs, ce projet cherche à
démontrer la capacité des outils statistiques à fournir des résultats
fiables et interprétables, tout en mettant en évidence l'importance du
choix méthodologique dans l'analyse des données réelles. \#\# 1.3
Description des données Les données utilisées dans ce projet proviennent
d'un ensemble de mesures physiologiques, anthropométriques et de
performance physique collectées auprès d'un échantillon d'individus.
Chaque observation correspond à un individu et regroupe des informations
démographiques, des caractéristiques corporelles ainsi que des
indicateurs de condition physique. Les variables étudiées ont été
sélectionnées afin de couvrir différents aspects de la condition
physique, no tamment la composition corporelle, la force musculaire,
l'endurance musculaire, la flexibilité et la capacité
cardiorespiratoire. La présence de variables qualitatives et
quantitatives permet de mener des analyses statistiques variées,
incluant des comparaisons de groupes et des tests d'hypothèses. La
variable sexe est utilisée comme variable de stratification afin
d'analyser les différences potentielles entre les groupes masculins et
féminins, tandis que les variables quantitatives sont exploitées pour
évaluer les relations statistiques et les performances physiques.
\textbar{} Variable \textbar{} Type \textbar{} Description \textbar{}
\textbar----------\textbar------\textbar-------------\textbar{}
\textbar{} sex \textbar{} Qualitative \textbar{} Sexe de l'individu
(M/F) \textbar{} \textbar{} age \textbar{} Quantitative \textbar{} Âge
de l'individu \textbar{} \textbar{} bmi \textbar{} Quantitative
\textbar{} Indice de masse corporelle \textbar{} \textbar{}
percent\_body\_fat \textbar{} Quantitative \textbar{} Pourcentage de
masse grasse \textbar{} \textbar{} hand\_grip\_strength\_kg \textbar{}
Quantitative \textbar{} Force de préhension \textbar{} \textbar{}
sit\_ups\_count \textbar{} Quantitative \textbar{} Nombre de sit-ups
\textbar{} \textbar{} sit\_and\_reach\_cm \textbar{} Quantitative
\textbar{} Flexibilité \textbar{} \textbar{}
vo2\_estimate\_ml\_per\_kg\_min \textbar{} Quantitative \textbar{} VO2
max estimé \textbar{}

\section{2 Importation et Préparation des
Données}\label{importation-et-pruxe9paration-des-donnuxe9es}

Cette section a pour objectif de présenter les étapes préliminaires
nécessaires à l'analyse statistique des données. Elle comprend le
chargement des bibliothèques requises, l'importation du jeu de données,
une exploration initiale des variables ainsi que l'étude de la
distribution des variables quantitatives. Ces étapes sont essentielles
pour assurer la qualité des analyses statistiques réalisées par la suite
et pour orienter le choix des méthodes appropriées. \#\# 2.1 Chargement
des packages L'analyse des données a été réalisée à l'aide du logiciel
R, en utilisant plusieurs bibliothèques spécialisées. Ces packages
permettent respectivement la lecture des fichiers de données, la
manipulation des données, la visualisation graphique, l'analyse
statistique et la modélisation. • openxlsx et readxl : importation de
fichiers Excel ; • dplyr et tidyr : manipulation et transformation des
données ; • ggplot2 et gridExtra : visualisation graphique ; • psych :
statistiques descriptives ; • corrplot : visualisation des corrélations
; • MASS : méthodes statistiques avancées, notamment la régression pas à
pas ; • naniar : détection et visualisation des valeurs manquantes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'readxl' a été compilé avec la version R 4.4.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'dplyr' a été compilé avec la version R 4.4.2
\end{verbatim}

\begin{verbatim}
## 
## Attachement du package : 'dplyr'
\end{verbatim}

\begin{verbatim}
## Les objets suivants sont masqués depuis 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## Les objets suivants sont masqués depuis 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'ggplot2' a été compilé avec la version R 4.4.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(corrplot)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'corrplot' a été compilé avec la version R 4.4.3
\end{verbatim}

\begin{verbatim}
## corrplot 0.95 loaded
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{2.2 Importation et exploration
initiale}\label{importation-et-exploration-initiale}

Le jeu de données est importé à partir d'un fichier Excel à l'aide de la
fonction read.xlsx. Une fois les données chargées, une exploration
initiale est réalisée afin de visualiser les premières observations, de
résumer les principales caractéristiques statistiques et d'examiner la
structure des variables. Les fonctions head(), summary() et str() sont
utilisées pour obtenir respectivement un aperçu des premières lignes du
jeu de données, des statistiques descriptives générales et des
informations sur le type de chaque variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"DATA.xlsx"}\NormalTok{)}

\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 10
##   participant_id sex     age measurement_date   bmi percent_body_fat
##            <dbl> <chr> <dbl> <chr>            <dbl>            <dbl>
## 1              1 M        46 2019-01-19        26.5             45  
## 2              2 M        25 2018-03-16        28.8             45  
## 3              3 M        53 2017-06-02        25.7             45  
## 4              4 M        46 2018-02-11        28               45  
## 5              5 F        32 2018-01-25        25               57.7
## 6              6 F        28 2018-11-06        24.7             60  
## # i 4 more variables: hand_grip_strength_kg <dbl>, sit_and_reach_cm <dbl>,
## #   sit_ups_count <dbl>, vo2_estimate_ml_per_kg_min <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2000   10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tibble [2,000 x 10] (S3: tbl_df/tbl/data.frame)
##  $ participant_id            : num [1:2000] 1 2 3 4 5 6 7 8 9 10 ...
##  $ sex                       : chr [1:2000] "M" "M" "M" "M" ...
##  $ age                       : num [1:2000] 46 25 53 46 32 28 34 34 49 60 ...
##  $ measurement_date          : chr [1:2000] "2019-01-19" "2018-03-16" "2017-06-02" "2018-02-11" ...
##  $ bmi                       : num [1:2000] 26.5 28.8 25.7 28 25 24.7 24.7 27.8 25 24.6 ...
##  $ percent_body_fat          : num [1:2000] 45 45 45 45 57.7 60 60 45 45 45 ...
##  $ hand_grip_strength_kg     : num [1:2000] 47 28 37.7 48.9 20 21.2 28.9 38.2 41.9 34.1 ...
##  $ sit_and_reach_cm          : num [1:2000] 13.4 -1.2 4.5 9 14.8 13.1 3.9 17.1 9.9 14.6 ...
##  $ sit_ups_count             : num [1:2000] 13 19 18 20 23 27 17 12 12 15 ...
##  $ vo2_estimate_ml_per_kg_min: num [1:2000] 29.8 46.5 37.2 52.5 24.6 30.1 30 45.7 39.5 28.8 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "participant_id"             "sex"                       
##  [3] "age"                        "measurement_date"          
##  [5] "bmi"                        "percent_body_fat"          
##  [7] "hand_grip_strength_kg"      "sit_and_reach_cm"          
##  [9] "sit_ups_count"              "vo2_estimate_ml_per_kg_min"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sapply}\NormalTok{(data, class)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             participant_id                        sex 
##                  "numeric"                "character" 
##                        age           measurement_date 
##                  "numeric"                "character" 
##                        bmi           percent_body_fat 
##                  "numeric"                  "numeric" 
##      hand_grip_strength_kg           sit_and_reach_cm 
##                  "numeric"                  "numeric" 
##              sit_ups_count vo2_estimate_ml_per_kg_min 
##                  "numeric"                  "numeric"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}

\NormalTok{data}\SpecialCharTok{$}\NormalTok{sex }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{sex)}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{measurement\_date }\OtherTok{\textless{}{-}} \FunctionTok{as.Date}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{measurement\_date)}

\ControlFlowTok{if}\NormalTok{(}\StringTok{"participant\_id"} \SpecialCharTok{\%in\%} \FunctionTok{colnames}\NormalTok{(data))\{}
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%}\NormalTok{dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{participant\_id)}
\NormalTok{\}}
\FunctionTok{head}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 9
##   sex     age measurement_date   bmi percent_body_fat hand_grip_strength_kg
##   <fct> <dbl> <date>           <dbl>            <dbl>                 <dbl>
## 1 M        46 2019-01-19        26.5             45                    47  
## 2 M        25 2018-03-16        28.8             45                    28  
## 3 M        53 2017-06-02        25.7             45                    37.7
## 4 M        46 2018-02-11        28               45                    48.9
## 5 F        32 2018-01-25        25               57.7                  20  
## 6 F        28 2018-11-06        24.7             60                    21.2
## # i 3 more variables: sit_and_reach_cm <dbl>, sit_ups_count <dbl>,
## #   vo2_estimate_ml_per_kg_min <dbl>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{num\_vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"age"}\NormalTok{,}
  \StringTok{"bmi"}\NormalTok{,}
  \StringTok{"percent\_body\_fat"}\NormalTok{,}
  \StringTok{"hand\_grip\_strength\_kg"}\NormalTok{,}
  \StringTok{"sit\_and\_reach\_cm"}\NormalTok{,}
  \StringTok{"sit\_ups\_count"}\NormalTok{,}
  \StringTok{"vo2\_estimate\_ml\_per\_kg\_min"}
\NormalTok{)}

\NormalTok{data\_numeric }\OtherTok{\textless{}{-}}\NormalTok{ data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(num\_vars))}

\FunctionTok{summary}\NormalTok{(data\_numeric)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       age             bmi        percent_body_fat hand_grip_strength_kg
##  Min.   :19.00   Min.   :15.00   Min.   :26.50    Min.   : 7.40        
##  1st Qu.:30.00   1st Qu.:21.80   1st Qu.:45.00    1st Qu.:27.88        
##  Median :41.00   Median :24.00   Median :45.00    Median :36.40        
##  Mean   :41.54   Mean   :23.98   Mean   :47.80    Mean   :35.96        
##  3rd Qu.:53.00   3rd Qu.:26.10   3rd Qu.:53.33    3rd Qu.:43.70        
##  Max.   :64.00   Max.   :37.10   Max.   :60.00    Max.   :68.00        
##  sit_and_reach_cm  sit_ups_count   vo2_estimate_ml_per_kg_min
##  Min.   :-14.900   Min.   : 5.00   Min.   :10.00             
##  1st Qu.:  3.700   1st Qu.:15.00   1st Qu.:31.50             
##  Median :  7.900   Median :17.00   Median :36.40             
##  Mean   :  7.887   Mean   :17.62   Mean   :36.28             
##  3rd Qu.: 11.900   3rd Qu.:20.00   3rd Qu.:41.20             
##  Max.   : 34.400   Max.   :33.00   Max.   :60.10
\end{verbatim}

\section{3 Analyse UNIVARIÉE}\label{analyse-univariuxe9e}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  sex           age        measurement_date          bmi        percent_body_fat
##  F: 645   Min.   :19.00   Min.   :2015-01-01   Min.   :15.00   Min.   :26.50   
##  M:1355   1st Qu.:30.00   1st Qu.:2016-04-07   1st Qu.:21.80   1st Qu.:45.00   
##           Median :41.00   Median :2017-06-29   Median :24.00   Median :45.00   
##           Mean   :41.54   Mean   :2017-07-01   Mean   :23.98   Mean   :47.80   
##           3rd Qu.:53.00   3rd Qu.:2018-09-18   3rd Qu.:26.10   3rd Qu.:53.33   
##           Max.   :64.00   Max.   :2019-12-31   Max.   :37.10   Max.   :60.00   
##  hand_grip_strength_kg sit_and_reach_cm  sit_ups_count  
##  Min.   : 7.40         Min.   :-14.900   Min.   : 5.00  
##  1st Qu.:27.88         1st Qu.:  3.700   1st Qu.:15.00  
##  Median :36.40         Median :  7.900   Median :17.00  
##  Mean   :35.96         Mean   :  7.887   Mean   :17.62  
##  3rd Qu.:43.70         3rd Qu.: 11.900   3rd Qu.:20.00  
##  Max.   :68.00         Max.   : 34.400   Max.   :33.00  
##  vo2_estimate_ml_per_kg_min
##  Min.   :10.00             
##  1st Qu.:31.50             
##  Median :36.40             
##  Mean   :36.28             
##  3rd Qu.:41.20             
##  Max.   :60.10
\end{verbatim}

\subsection{3.1 Prépartion des
données}\label{pruxe9partion-des-donnuxe9es}

\subsubsection{3.1.1 Vérification des
doublons}\label{vuxe9rification-des-doublons}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{duplicated}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\#\#\#3.1.2 Vérification des valeurs manquantes

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(data))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                        sex                        age 
##                          0                          0 
##           measurement_date                        bmi 
##                          0                          0 
##           percent_body_fat      hand_grip_strength_kg 
##                          0                          0 
##           sit_and_reach_cm              sit_ups_count 
##                          0                          0 
## vo2_estimate_ml_per_kg_min 
##                          0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(naniar)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'naniar' a été compilé avec la version R 4.4.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{vis\_miss}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-6-1.pdf}}
\#\#\# 3.1.3 Vérification des valeurs aberrantes

Ladétectiondesvaleursaberrantesconstitueuneétape importantede
l'analyseexploratoiredesdonnées,
carlaprésenced'observationsextrêmespeutinfluencerlesstatistiquesdescriptives,
lestestsd'hypothèseset lesmodèlesstatistiquesultérieurs. Dans cette
étude, lesvaleurs aberrantes sont identifiées à
l'aided'uneapprochegraphiquebasée sur les boxplots. Afindefaciliter
lacomparaisonsimultanéedesdifférentesvariablesnumériques, lesdonnéessont
d'abord transformées au format long, chaque observationétant associée
àunevariable et àunevaleur correspondante. Lesboxplotsreprésentent
ladistributiondesdonnéesàl'aidede lamédiane,desquartilesetdesétendues
interquartiles.Lesobservationssituéesendehorsdesbornesdéfiniesparl'intervalle{[}𝑄1−1.5×𝐼𝑄𝑅,𝑄3+
1.5×𝐼𝑄𝑅{]}sontconsidéréescommedesvaleursaberrantesetsontmisesenévidencegraphiquement.
Cettevisualisationpermetd'identifierrapidementlesvariablesprésentantunefortedispersionouunnombre
importantdevaleursextrêmes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ==================================================}
\CommentTok{\# ANALYSE ET CORRECTION DES VALEURS ABERRANTES}
\CommentTok{\# ==================================================}

\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 1. Fonction de détection}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{detecter\_outliers }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(variable, nom\_variable)\{}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{====================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Analyse de :"}\NormalTok{, nom\_variable, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"====================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}

\CommentTok{\# Calcul Q1 et Q3}
\NormalTok{Q1 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(variable, }\FloatTok{0.25}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{Q3 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(variable, }\FloatTok{0.75}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Calcul IQR}
\NormalTok{IQR\_value }\OtherTok{\textless{}{-}}\NormalTok{ Q3 }\SpecialCharTok{{-}}\NormalTok{ Q1}

\CommentTok{\# Limites}
\NormalTok{limite\_basse }\OtherTok{\textless{}{-}}\NormalTok{ Q1 }\SpecialCharTok{{-}} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR\_value}
\NormalTok{limite\_haute }\OtherTok{\textless{}{-}}\NormalTok{ Q3 }\SpecialCharTok{+} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR\_value}

\CommentTok{\# Détection outliers}
\NormalTok{outliers\_bas }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(variable }\SpecialCharTok{\textless{}}\NormalTok{ limite\_basse, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{outliers\_haut }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(variable }\SpecialCharTok{\textgreater{}}\NormalTok{ limite\_haute, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{total\_outliers }\OtherTok{\textless{}{-}}\NormalTok{ outliers\_bas }\SpecialCharTok{+}\NormalTok{ outliers\_haut}

\CommentTok{\# Affichage}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Outliers bas :"}\NormalTok{, outliers\_bas, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Outliers haut :"}\NormalTok{, outliers\_haut, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Total :"}\NormalTok{, total\_outliers, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Limite basse :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(limite\_basse,}\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Limite haute :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(limite\_haute,}\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}

\FunctionTok{return}\NormalTok{(}\FunctionTok{list}\NormalTok{(}
\AttributeTok{limite\_basse =}\NormalTok{ limite\_basse,}
\AttributeTok{limite\_haute =}\NormalTok{ limite\_haute}
\NormalTok{))}
\NormalTok{\}}

\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# 2. Fonction de correction}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{corriger\_outliers }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(variable)\{}

\NormalTok{Q1 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(variable, }\FloatTok{0.25}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{Q3 }\OtherTok{\textless{}{-}} \FunctionTok{quantile}\NormalTok{(variable, }\FloatTok{0.75}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{IQR\_value }\OtherTok{\textless{}{-}}\NormalTok{ Q3 }\SpecialCharTok{{-}}\NormalTok{ Q1}

\NormalTok{limite\_basse }\OtherTok{\textless{}{-}}\NormalTok{ Q1 }\SpecialCharTok{{-}} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR\_value}
\NormalTok{limite\_haute }\OtherTok{\textless{}{-}}\NormalTok{ Q3 }\SpecialCharTok{+} \FloatTok{1.5} \SpecialCharTok{*}\NormalTok{ IQR\_value}

\CommentTok{\# Copie variable}
\NormalTok{variable\_corrigee }\OtherTok{\textless{}{-}}\NormalTok{ variable}

\CommentTok{\# Winsorization}
\NormalTok{variable\_corrigee[variable }\SpecialCharTok{\textless{}}\NormalTok{ limite\_basse] }\OtherTok{\textless{}{-}}\NormalTok{ limite\_basse}
\NormalTok{variable\_corrigee[variable }\SpecialCharTok{\textgreater{}}\NormalTok{ limite\_haute] }\OtherTok{\textless{}{-}}\NormalTok{ limite\_haute}

\FunctionTok{return}\NormalTok{(variable\_corrigee)}
\NormalTok{\}}

\CommentTok{\# ==================================================}
\CommentTok{\# 3. ANALYSE DES VALEURS ABERRANTES}
\CommentTok{\# ==================================================}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{ANALYSE DES VALEURS ABERRANTES}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ANALYSE DES VALEURS ABERRANTES
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"====================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ====================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{variables\_numeriques }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
\StringTok{"age"}\NormalTok{,}
\StringTok{"bmi"}\NormalTok{,}
\StringTok{"percent\_body\_fat"}\NormalTok{,}
\StringTok{"hand\_grip\_strength\_kg"}\NormalTok{,}
\StringTok{"sit\_and\_reach\_cm"}\NormalTok{,}
\StringTok{"sit\_ups\_count"}\NormalTok{,}
\StringTok{"vo2\_estimate\_ml\_per\_kg\_min"}
\NormalTok{)}

\CommentTok{\# Analyse de chaque variable}
\ControlFlowTok{for}\NormalTok{(var }\ControlFlowTok{in}\NormalTok{ variables\_numeriques)\{}

\ControlFlowTok{if}\NormalTok{(var }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(data))\{}

\FunctionTok{detecter\_outliers}\NormalTok{(data[[var]], var)}

\NormalTok{\}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ====================================
## Analyse de : age 
## ====================================
## Outliers bas : 0 
## Outliers haut : 0 
## Total : 0 
## Limite basse : -4.5 
## Limite haute : 87.5 
## 
## ====================================
## Analyse de : bmi 
## ====================================
## Outliers bas : 8 
## Outliers haut : 5 
## Total : 13 
## Limite basse : 15.35 
## Limite haute : 32.55 
## 
## ====================================
## Analyse de : percent_body_fat 
## ====================================
## Outliers bas : 14 
## Outliers haut : 0 
## Total : 14 
## Limite basse : 32.51 
## Limite haute : 65.81 
## 
## ====================================
## Analyse de : hand_grip_strength_kg 
## ====================================
## Outliers bas : 0 
## Outliers haut : 1 
## Total : 1 
## Limite basse : 4.14 
## Limite haute : 67.44 
## 
## ====================================
## Analyse de : sit_and_reach_cm 
## ====================================
## Outliers bas : 10 
## Outliers haut : 7 
## Total : 17 
## Limite basse : -8.6 
## Limite haute : 24.2 
## 
## ====================================
## Analyse de : sit_ups_count 
## ====================================
## Outliers bas : 15 
## Outliers haut : 32 
## Total : 47 
## Limite basse : 7.5 
## Limite haute : 27.5 
## 
## ====================================
## Analyse de : vo2_estimate_ml_per_kg_min 
## ====================================
## Outliers bas : 5 
## Outliers haut : 7 
## Total : 12 
## Limite basse : 16.95 
## Limite haute : 55.75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ==================================================}
\CommentTok{\# 4. CORRECTION DES OUTLIERS}
\CommentTok{\# ==================================================}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{CORRECTION DES VALEURS ABERRANTES}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## CORRECTION DES VALEURS ABERRANTES
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"====================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ====================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Copie dataset}
\NormalTok{health\_clean }\OtherTok{\textless{}{-}}\NormalTok{ data}

\CommentTok{\# Variables à corriger}
\NormalTok{variables\_a\_corriger }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
\StringTok{"bmi"}\NormalTok{,}
\StringTok{"percent\_body\_fat"}\NormalTok{,}
\StringTok{"hand\_grip\_strength\_kg"}
\NormalTok{)}

\ControlFlowTok{for}\NormalTok{(var }\ControlFlowTok{in}\NormalTok{ variables\_a\_corriger)\{}

\ControlFlowTok{if}\NormalTok{(var }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(data))\{}

\NormalTok{avant }\OtherTok{\textless{}{-}}\NormalTok{ data[[var]]}

\NormalTok{apres }\OtherTok{\textless{}{-}} \FunctionTok{corriger\_outliers}\NormalTok{(avant)}

\NormalTok{health\_clean[[var]] }\OtherTok{\textless{}{-}}\NormalTok{ apres}

\NormalTok{modifications }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(avant }\SpecialCharTok{!=}\NormalTok{ apres, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(var, }\StringTok{":"}\NormalTok{, modifications, }\StringTok{"valeurs corrigées}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## bmi : 13 valeurs corrigées
## percent_body_fat : 14 valeurs corrigées
## hand_grip_strength_kg : 1 valeurs corrigées
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ==================================================}
\CommentTok{\# 5. COMPARAISON AVANT / APRES}
\CommentTok{\# ==================================================}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{COMPARAISON AVANT/APRES}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## COMPARAISON AVANT/APRES
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"====================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ====================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{comparer\_stats }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(avant, apres, nom)\{}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Variable :"}\NormalTok{, nom, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"AVANT {-}\textgreater{} "}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Min :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{min}\NormalTok{(avant, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}\DecValTok{2}\NormalTok{),}
\StringTok{"Max :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{max}\NormalTok{(avant, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}\DecValTok{2}\NormalTok{),}
\StringTok{"Moyenne :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(avant, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"APRES {-}\textgreater{} "}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Min :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{min}\NormalTok{(apres, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}\DecValTok{2}\NormalTok{),}
\StringTok{"Max :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{max}\NormalTok{(apres, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}\DecValTok{2}\NormalTok{),}
\StringTok{"Moyenne :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(apres, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}

\ControlFlowTok{for}\NormalTok{(var }\ControlFlowTok{in}\NormalTok{ variables\_a\_corriger)\{}

\ControlFlowTok{if}\NormalTok{(var }\SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(data))\{}

\FunctionTok{comparer\_stats}\NormalTok{(}
\NormalTok{data[[var]],}
\NormalTok{health\_clean[[var]],}
\NormalTok{var}
\NormalTok{)}

\NormalTok{\}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Variable : bmi 
## AVANT -> Min : 15 Max : 37.1 Moyenne : 23.98 
## APRES -> Min : 15.35 Max : 32.55 Moyenne : 23.98 
## 
## Variable : percent_body_fat 
## AVANT -> Min : 26.5 Max : 60 Moyenne : 47.8 
## APRES -> Min : 32.51 Max : 60 Moyenne : 47.81 
## 
## Variable : hand_grip_strength_kg 
## AVANT -> Min : 7.4 Max : 68 Moyenne : 35.96 
## APRES -> Min : 7.4 Max : 67.44 Moyenne : 35.96
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ==================================================}
\CommentTok{\# 6. VISUALISATION}
\CommentTok{\# ==================================================}

\FunctionTok{library}\NormalTok{(ggplot2)}

\NormalTok{data\_compare }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{()}

\ControlFlowTok{for}\NormalTok{(var }\ControlFlowTok{in}\NormalTok{ variables\_a\_corriger)\{}

\NormalTok{temp }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
\AttributeTok{Valeur =} \FunctionTok{c}\NormalTok{(data[[var]], health\_clean[[var]]),}
\AttributeTok{Variable =}\NormalTok{ var,}
\AttributeTok{Statut =} \FunctionTok{rep}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Avant"}\NormalTok{, }\StringTok{"Après"}\NormalTok{),}
\AttributeTok{each =} \FunctionTok{nrow}\NormalTok{(data))}
\NormalTok{)}

\NormalTok{data\_compare }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(data\_compare, temp)}
\NormalTok{\}}

\CommentTok{\# Boxplot comparatif}

\FunctionTok{ggplot}\NormalTok{(data\_compare,}
\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Variable,}
\AttributeTok{y =}\NormalTok{ Valeur,}
\AttributeTok{fill =}\NormalTok{ Statut)) }\SpecialCharTok{+}

\FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}

\FunctionTok{labs}\NormalTok{(}
\AttributeTok{title =} \StringTok{"Comparaison avant/après correction des outliers"}\NormalTok{,}
\AttributeTok{x =} \StringTok{"Variables"}\NormalTok{,}
\AttributeTok{y =} \StringTok{"Valeurs"}
\NormalTok{) }\SpecialCharTok{+}

\FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-7-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Sauvegarde dataset nettoyé}

\FunctionTok{write.csv}\NormalTok{(}
\NormalTok{health\_clean,}
\StringTok{"health\_dataset\_clean.csv"}\NormalTok{,}
\AttributeTok{row.names =} \ConstantTok{FALSE}
\NormalTok{)}

\CommentTok{\# ==================================================}
\CommentTok{\# RAPPORT FINAL}
\CommentTok{\# ==================================================}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{RAPPORT FINAL}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## RAPPORT FINAL
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"====================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ====================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{total\_observations }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(health\_clean)}

\NormalTok{total\_variables }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(variables\_numeriques)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Observations totales :"}\NormalTok{, total\_observations, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Observations totales : 2000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Variables nettoyées :"}\NormalTok{, total\_variables, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Variables nettoyées : 7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Fichier sauvegardé : health\_dataset\_clean.csv}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Fichier sauvegardé : health_dataset_clean.csv
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Nettoyage terminé avec succès !}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Nettoyage terminé avec succès !
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Aperçu final}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{APERÇU DU DATASET NETTOYÉ :}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## APERÇU DU DATASET NETTOYÉ :
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{head}\NormalTok{(health\_clean))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 9
##   sex     age measurement_date   bmi percent_body_fat hand_grip_strength_kg
##   <fct> <dbl> <date>           <dbl>            <dbl>                 <dbl>
## 1 M        46 2019-01-19        26.5             45                    47  
## 2 M        25 2018-03-16        28.8             45                    28  
## 3 M        53 2017-06-02        25.7             45                    37.7
## 4 M        46 2018-02-11        28               45                    48.9
## 5 F        32 2018-01-25        25               57.7                  20  
## 6 F        28 2018-11-06        24.7             60                    21.2
## # i 3 more variables: sit_and_reach_cm <dbl>, sit_ups_count <dbl>,
## #   vo2_estimate_ml_per_kg_min <dbl>
\end{verbatim}

\#\#3.2 Vérification de la densité des variables
L'étudedeladistributiondesvariablesquantitativesconstitueuneétapeclédel'analyseexploratoire.Elle
permetd'évaluervisuellement
laformedesdistributions,d'identifierd'éventuellesasymétriesetd'anticiper
lechoixdestestsstatistiquesappropriés. Pour chaquevariablenumérique,
unhistogrammeaccompagnéde sacourbededensité est tracé. Cette
représentationgraphique facilite l'appréciationde lanormalitéoude
lanon-normalitédesdistributionset
metenévidencelaprésenceéventuelledevaleursextrêmes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}

\CommentTok{\# Variables à analyser}

\NormalTok{target\_vars }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
\StringTok{"hand\_grip\_strength\_kg"}\NormalTok{,}
\StringTok{"sit\_and\_reach\_cm"}\NormalTok{,}
\StringTok{"sit\_ups\_count"}\NormalTok{,}
\StringTok{"vo2\_estimate\_ml\_per\_kg\_min"}
\NormalTok{)}

\CommentTok{\# Boucle analyse}

\ControlFlowTok{for}\NormalTok{(var }\ControlFlowTok{in}\NormalTok{ target\_vars)\{}

\FunctionTok{cat}\NormalTok{(}\StringTok{"{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Variable :"}\NormalTok{, var, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}

\NormalTok{x }\OtherTok{\textless{}{-}}\NormalTok{ health\_clean[[var]]}

\CommentTok{\# ==================================================}
\CommentTok{\# 1. Résumé statistique}
\CommentTok{\# ==================================================}

\FunctionTok{print}\NormalTok{(}\FunctionTok{summary}\NormalTok{(x))}

\CommentTok{\# ==================================================}
\CommentTok{\# 2. Histogramme + densité}
\CommentTok{\# ==================================================}

\NormalTok{mean\_x }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{sd\_x }\OtherTok{\textless{}{-}} \FunctionTok{sd}\NormalTok{(x, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x)}

\NormalTok{p1 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(x)) }\SpecialCharTok{+}

\FunctionTok{geom\_histogram}\NormalTok{(}
\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..),}
\AttributeTok{bins =} \DecValTok{30}\NormalTok{,}
\AttributeTok{fill =} \StringTok{"lightblue"}\NormalTok{,}
\AttributeTok{alpha =} \FloatTok{0.6}
\NormalTok{) }\SpecialCharTok{+}

\FunctionTok{geom\_density}\NormalTok{(}
\AttributeTok{color =} \StringTok{"red"}\NormalTok{,}
\AttributeTok{linewidth =} \FloatTok{1.2}
\NormalTok{) }\SpecialCharTok{+}

\FunctionTok{stat\_function}\NormalTok{(}
\AttributeTok{fun =}\NormalTok{ dnorm,}
\AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =}\NormalTok{ mean\_x, }\AttributeTok{sd =}\NormalTok{ sd\_x),}
\AttributeTok{color =} \StringTok{"darkgreen"}\NormalTok{,}
\AttributeTok{linewidth =} \FloatTok{1.2}
\NormalTok{) }\SpecialCharTok{+}

\FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}

\FunctionTok{labs}\NormalTok{(}
\AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Distribution {-}"}\NormalTok{, var),}
\AttributeTok{x =}\NormalTok{ var,}
\AttributeTok{y =} \StringTok{"Densité"}
\NormalTok{)}

\FunctionTok{print}\NormalTok{(p1)}

\CommentTok{\# ==================================================}
\CommentTok{\# 3. QQ Plot}
\CommentTok{\# ==================================================}

\NormalTok{p2 }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample =}\NormalTok{ x)) }\SpecialCharTok{+}

\FunctionTok{stat\_qq}\NormalTok{(}\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}

\FunctionTok{stat\_qq\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"red"}\NormalTok{) }\SpecialCharTok{+}

\FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}

\FunctionTok{labs}\NormalTok{(}
\AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"QQ Plot {-}"}\NormalTok{, var)}
\NormalTok{)}

\FunctionTok{print}\NormalTok{(p2)}

\CommentTok{\# ==================================================}
\CommentTok{\# 4. Test Shapiro{-}Wilk}
\CommentTok{\# ==================================================}

\ControlFlowTok{if}\NormalTok{(}\FunctionTok{length}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(x)) }\SpecialCharTok{\textless{}=} \DecValTok{5000}\NormalTok{)\{}

\NormalTok{sh }\OtherTok{\textless{}{-}} \FunctionTok{shapiro.test}\NormalTok{(x)}

\FunctionTok{print}\NormalTok{(sh)}

\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Shapiro non applicable (\textgreater{}5000 observations)}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}

\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## --------------------------------------------------
## Variable : hand_grip_strength_kg 
## --------------------------------------------------
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    7.40   27.88   36.40   35.96   43.70   67.44
\end{verbatim}

\begin{verbatim}
## Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
## i Please use `after_stat(density)` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-1.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-2.pdf}}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  x
## W = 0.99336, p-value = 7.622e-08
## 
## 
## 
## --------------------------------------------------
## Variable : sit_and_reach_cm 
## --------------------------------------------------
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -14.900   3.700   7.900   7.887  11.900  34.400
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-3.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-4.pdf}}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  x
## W = 0.99911, p-value = 0.441
## 
## 
## 
## --------------------------------------------------
## Variable : sit_ups_count 
## --------------------------------------------------
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5.00   15.00   17.00   17.62   20.00   33.00
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-5.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-6.pdf}}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  x
## W = 0.99218, p-value = 7.357e-09
## 
## 
## 
## --------------------------------------------------
## Variable : vo2_estimate_ml_per_kg_min 
## --------------------------------------------------
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   10.00   31.50   36.40   36.28   41.20   60.10
\end{verbatim}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-7.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-8-8.pdf}}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  x
## W = 0.99956, p-value = 0.9484
\end{verbatim}

\#3.3 Standardisation: Avant de réaliser l'Analyse en Composantes
Principales (ACP), il est nécessaire de standardiser les variables
quantitatives. En effet, les variables étudiées ne sont pas exprimées
dans les mêmes unités (kg, cm, années, etc.), ce qui pourrait biaiser
l'analyse en donnant plus de poids aux variables ayant de grandes
valeurs numériques.

La standardisation permet donc de transformer les variables afin
qu'elles aient une moyenne nulle et un écart-type égal à 1. Cette étape
garantit que toutes les variables contribuent de manière équivalente à
l'ACP.

Dans cette étude, nous sélectionnons uniquement les variables
quantitatives issues du jeu de données nettoyé, puis nous appliquons la
méthode de standardisation avant de réaliser l'ACP.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(FactoMineR)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'FactoMineR' a été compilé avec la version R 4.4.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(factoextra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: le package 'factoextra' a été compilé avec la version R 4.4.3
\end{verbatim}

\begin{verbatim}
## Welcome to factoextra!
\end{verbatim}

\begin{verbatim}
## Want to learn more? See two factoextra-related books at https://www.datanovia.com/en/product/practical-guide-to-principal-component-methods-in-r/
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{variables\_quantitatives }\OtherTok{\textless{}{-}}\NormalTok{ num\_vars}

\NormalTok{data\_numeric }\OtherTok{\textless{}{-}}\NormalTok{ health\_clean }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{all\_of}\NormalTok{(variables\_quantitatives))}

\NormalTok{data\_scaled }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(data\_numeric)}
\end{Highlighting}
\end{Shaded}

Les données standardisées sont ensuite utilisées pour réaliser l'ACP
afin d'explorer les relations entre les variables et réduire la
dimension des données.

\#4 Analyse Factorielle : ACP (Analyse en Composantes Principales) \#\#
4.1 Objectif de l'Analyse en Composantes Principales (ACP) L'Analyse en
Composantes Principales (ACP) a été réalisée afin de réduire la
dimension des données physiologiques et anthropométriques tout en
conservant le maximum d'information contenue dans les variables
initiales. Cette méthode permet également d'identifier les relations
existantes entre les variables étudiées ainsi que les profils des
individus selon leurs caractéristiques physiques et physiologiques.

Les variables quantitatives utilisées dans l'analyse sont :

âge ; indice de masse corporelle (IMC) ; pourcentage de masse grasse ;
force de préhension manuelle ; flexibilité ; endurance abdominale
(sit-ups) ; capacité cardiovasculaire estimée (VO2max).

Avant l'ACP, les données ont été standardisées afin d'éliminer l'effet
des différences d'unités de mesure entre les variables.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res.pca }\OtherTok{\textless{}{-}} \FunctionTok{PCA}\NormalTok{(data\_scaled, }\AttributeTok{graph =} \ConstantTok{FALSE}\NormalTok{)}

\NormalTok{eig.val }\OtherTok{\textless{}{-}} \FunctionTok{get\_eigenvalue}\NormalTok{(res.pca)}
\NormalTok{eig.val}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       eigenvalue variance.percent cumulative.variance.percent
## Dim.1  1.9702193        28.145991                    28.14599
## Dim.2  1.2944069        18.491527                    46.63752
## Dim.3  1.1507254        16.438934                    63.07645
## Dim.4  0.9400499        13.429285                    76.50574
## Dim.5  0.7857555        11.225078                    87.73082
## Dim.6  0.5765042         8.235774                    95.96659
## Dim.7  0.2823388         4.033411                   100.00000
\end{verbatim}

La première composante principale explique :

28.1\%

de la variance totale des données.

Cela signifie que près d'un tiers de l'information contenue dans
l'ensemble des variables peut être résumé par un seul axe factoriel.

La deuxième composante explique :

18.5\%

de la variance supplémentaire.

Ainsi, les deux premiers axes résument ensemble :

46.6\%

de l'information totale.

Ce résultat est satisfaisant dans le contexte des données biométriques
et physiologiques, où les phénomènes étudiés sont généralement complexes
et multidimensionnels.

Les trois premières composantes principales expliquent :

63.1\%

de la variance totale, ce qui indique une bonne qualité globale de
représentation des données.

Selon le critère de Kaiser :

λ\textgreater1

les trois premières dimensions peuvent être retenues puisqu'elles
possèdent des valeurs propres supérieures à 1. \#\# 4.2 Graphiques ACP
\#\#\# 4.2.1 Diagramme des valeurs propres (Scree Plot)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_eig}\NormalTok{(res.pca, }\AttributeTok{addlabels =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-11-1.pdf}}
Ce graphique montre :

l'importance de chaque composante principale ; la quantité de variance
expliquée par chaque axe ; le nombre d'axes à conserver.

Le diagramme des valeurs propres montre que les premières composantes
principales concentrent une part importante de l'information du dataset.

La première dimension explique à elle seule 28.1 \% de la variance
totale, tandis que les deux premières dimensions représentent environ
46.6 \% de l'information globale.

Les trois premières composantes principales permettent de conserver plus
de 63 \% de la variance totale, ce qui constitue une représentation
satisfaisante des données multidimensionnelles.

Selon le critère de Kaiser, les trois premières composantes ont été
retenues car leurs valeurs propres sont supérieures à 1. \#\#\#4.2.2
Cercle des corrélations des variables

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_pca\_var}\NormalTok{(res.pca)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-12-1.pdf}}
Le cercle des corrélations met en évidence plusieurs relations
significatives entre les variables biométriques et physiques.

Les variables bmi et percent\_body\_fat sont fortement corrélées
positivement, indiquant qu'une augmentation de l'indice de masse
corporelle est généralement associée à une augmentation du pourcentage
de graisse corporelle.

Les variables liées à la performance physique, notamment
vo2\_estimate\_ml\_per\_kg\_min et sit\_ups\_count, apparaissent proches
les unes des autres, traduisant une relation positive entre endurance
cardiovasculaire et performance musculaire.

Une opposition est observée entre les variables de performance physique
et les variables de composition corporelle, ce qui suggère qu'un taux
élevé de graisse corporelle est associé à une moins bonne condition
physique.

La variable age semble moins bien représentée sur les deux premiers axes
factoriels, indiquant une contribution plus modérée à la structure
principale des données. \#\#\#4.2.3 Contribution des variables à la
première composante principale

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_contrib}\NormalTok{(res.pca, }\AttributeTok{choice =} \StringTok{"var"}\NormalTok{, }\AttributeTok{axes =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-13-1.pdf}}
Ce graphique montre :

quelles variables contribuent le plus à l'axe 1 ; quelles variables
définissent la première dimension La première composante principale est
principalement construite par les variables liées à la condition
physique générale.

Les variables hand\_grip\_strength\_kg, vo2\_estimate\_ml\_per\_kg\_min
et sit\_ups\_count contribuent fortement à cet axe, traduisant les
capacités physiques et cardiovasculaires des individus.

À l'inverse, la variable percent\_body\_fat apparaît opposée aux
variables de performance, indiquant qu'un taux élevé de graisse
corporelle est associé à des performances physiques plus faibles.

Cette dimension peut ainsi être interprétée comme un axe global de
condition physique et de santé. \#\#\#4.2.4 Contribution des variables à
la deuxième composante principale

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_contrib}\NormalTok{(res.pca, }\AttributeTok{choice =} \StringTok{"var"}\NormalTok{, }\AttributeTok{axes =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-14-1.pdf}}
Ce graphique identifie :

les variables qui expliquent la deuxième dimension ; la signification
statistique de l'axe 2. La deuxième composante principale semble
principalement liée à l'endurance physique et aux caractéristiques
physiologiques des individus.

Les variables age, vo2\_estimate\_ml\_per\_kg\_min et sit\_ups\_count
présentent les contributions les plus importantes sur cet axe.

Cette dimension traduit une différenciation des individus selon leur
capacité cardiovasculaire et leur profil physiologique global.
\#\#\#4.2.5 Projection des individus sur le plan factoriel

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_pca\_ind}\NormalTok{(res.pca) }
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-15-1.pdf}}
Ce graphique permet :

de visualiser les individus ; d'identifier des regroupements ; de
détecter des profils similaires ou atypiques.

La projection des individus sur le plan factoriel montre une dispersion
relativement importante des observations, ce qui traduit une forte
diversité des profils physiques présents dans le dataset.

Certains regroupements apparaissent néanmoins, suggérant l'existence de
profils homogènes d'individus partageant des caractéristiques physiques
similaires.

Cette structuration des données justifie l'utilisation ultérieure de
méthodes de classification telles que le clustering K-Means. \#\#\#4.2.6
Qualité de représentation des variables (Cos²)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_cos2}\NormalTok{(res.pca, }\AttributeTok{choice =} \StringTok{"var"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-16-1.pdf}}
Ce graphique mesure :

la qualité de représentation des variables ; quelles variables sont bien
expliquées par les axes factoriels. Les variables
hand\_grip\_strength\_kg, percent\_body\_fat et
vo2\_estimate\_ml\_per\_kg\_min présentent les meilleurs cos², indiquant
qu'elles sont correctement représentées sur le plan factoriel formé par
les deux premières composantes principales.

À l'inverse, la variable sit\_and\_reach\_cm présente une qualité de
représentation plus faible, ce qui signifie qu'elle est moins bien
expliquée par les deux premières dimensions de l'ACP.

\#\#\#4.2.7 ACP avec variable illustrative SEXE(Projection des individus
selon le sexe)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_pca\_ind}\NormalTok{(}
\NormalTok{res.pca,}
\AttributeTok{habillage =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{sex}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-17-1.pdf}}
Ce graphique permet :

de comparer hommes et femmes ; d'observer les différences physiologiques
entre groupes. L'ajout de la variable illustrative sex met en évidence
certaines différences entre les profils masculins et féminins.

Les individus présentent des répartitions partiellement distinctes sur
le plan factoriel, traduisant des différences physiologiques et
physiques entre les deux groupes.

Cette séparation reste toutefois partielle, ce qui suggère également
l'existence de caractéristiques communes entre les individus
indépendamment du sexe. \#\#\#4.2.8 Corrélation entre variables

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(corrplot)}

\FunctionTok{corrplot}\NormalTok{(}
\FunctionTok{cor}\NormalTok{(data\_scaled),}
\AttributeTok{method =} \StringTok{"color"}\NormalTok{,}
\AttributeTok{type =} \StringTok{"upper"}\NormalTok{,}
\AttributeTok{addCoef.col =} \StringTok{"black"}\NormalTok{,}
\AttributeTok{tl.col =} \StringTok{"black"}\NormalTok{,}
\AttributeTok{tl.cex =} \FloatTok{0.7}\NormalTok{,}
\AttributeTok{number.cex =} \FloatTok{0.6}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{rapport_files/rapport_files/figure-latex/unnamed-chunk-18-1.pdf}}
La matrice des corrélations met en évidence plusieurs relations
significatives entre les variables biométriques et physiques.

Une forte corrélation positive est observée entre les variables bmi et
percent\_body\_fat, traduisant une relation directe entre l'indice de
masse corporelle et le taux de graisse corporelle.

Les variables liées aux performances physiques, notamment
vo2\_estimate\_ml\_per\_kg\_min, sit\_ups\_count et
hand\_grip\_strength\_kg, présentent également des corrélations
positives, indiquant une cohérence globale des indicateurs de condition
physique.

À l'inverse, les variables associées à la composition corporelle
apparaissent négativement corrélées aux variables de performance
physique, suggérant qu'un excès de graisse corporelle est associé à une
diminution des capacités physiques.

Cette structure de corrélation justifie pleinement l'utilisation de
l'Analyse en Composantes Principales afin de résumer les relations
multidimensionnelles entre les variables.

\#\#4.3 Conclusion ACP : L'Analyse en Composantes Principales a permis
de mettre en évidence les principales structures statistiques des
données physiologiques et anthropométriques.

Les résultats montrent que :

la première composante principale représente essentiellement le niveau
global de condition physique ; la deuxième composante est principalement
liée à l'âge ; la masse grasse est négativement associée aux
performances physiques ; les capacités musculaires et cardiovasculaires
sont positivement corrélées ; les différences entre les sexes existent
mais restent partiellement superposées.

L'ACP a ainsi permis de réduire efficacement la dimension des données
tout en conservant une proportion importante de l'information initiale.

\end{document}
